// pizza/pizza-react-frontend/src/components/ProductCard.tsx
import { memo } from 'react';
import { Button, Card } from 'react-bootstrap';
import type { Product } from '../types';
import { formatMoney } from '../lib/money';

interface Props {
  product: Product;
  onSelect: (product: Product) => void;
}

/* ==========================================================================
 * REACT CONCEPT: React.memo
 *
 * memo skips re-rendering a component when its props are unchanged (compared shallowly).
 *
 * It matters here because the menu renders 14 of these. Without memo, opening the cart drawer —
 * which changes state in a PARENT — would re-render all 14 cards even though not one of their
 * props changed.
 *
 * memo only works if the props are referentially stable. That is exactly why `onSelect` is
 * wrapped in useCallback by the parent: an inline arrow function would be a new object on every
 * render and memo would never hit.
 *
 * Do not reach for memo by default. It costs a comparison on every render and is only worth it
 * for components that are numerous, expensive, or both.
 * ========================================================================== */
export const ProductCard = memo(function ProductCard({ product, onSelect }: Props) {
  const cheapest = Math.min(...product.sizes.map((s) => s.price));
  const isPizza = product.type === 'PIZZA';

  return (
    <Card className="product-card">
      <div className="product-thumb" aria-hidden="true">
        {isPizza ? '🍕' : '🥤'}
      </div>
      <Card.Body className="d-flex flex-column">
        <Card.Title as="h3" className="h6 fw-bold mb-1">
          {product.name}
        </Card.Title>
        <Card.Text className="text-muted small flex-grow-1">{product.description}</Card.Text>
        <div className="d-flex justify-content-between align-items-center mt-2">
          <span className="fw-bold">
            from <span className="text-pizza-red">{formatMoney(cheapest)}</span>
          </span>
          <Button size="sm" variant="primary" onClick={() => onSelect(product)}>
            {isPizza ? 'Build it' : 'Add'}
          </Button>
        </div>
      </Card.Body>
    </Card>
  );
});

// pizza/pizza-angular-frontend/src/app/shared/product-card/product-card.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { MoneyPipe } from '../../core/money.pipe';
import type { Product } from '../../core/models';

/* ==========================================================================
 * ANGULAR CONCEPT: OnPush is the built-in React.memo
 *
 * The React version of this card is wrapped in `React.memo`, and the menu page has to wrap its
 * `onSelect` handler in `useCallback` for the memo to hit at all — an inline arrow would be a new
 * function identity on every render and the comparison would never succeed.
 *
 * `ChangeDetectionStrategy.OnPush` gets the same result without either. Angular re-checks this
 * component only when an input reference changes or a signal it read changes; a handler bound with
 * `(selected)="…"` in the parent is not an input, so it cannot invalidate anything. There is no
 * `useCallback` in Angular because there is nothing for it to fix.
 *
 * The other half of the React comment still applies to both: do not reach for this by default. It
 * is worth it for components that are numerous, expensive, or both. Fourteen of these render on
 * the menu page, which qualifies.
 * ========================================================================== */
@Component({
  selector: 'app-product-card',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MoneyPipe],
  template: `
    <div class="card product-card">
      <div class="product-thumb" aria-hidden="true">{{ isPizza() ? '🍕' : '🥤' }}</div>
      <div class="card-body d-flex flex-column">
        <h3 class="card-title h6 fw-bold mb-1">{{ product().name }}</h3>
        <p class="card-text text-muted small flex-grow-1">{{ product().description }}</p>
        <div class="d-flex justify-content-between align-items-center mt-2">
          <span class="fw-bold">
            from <span class="text-pizza-red">{{ cheapest() | money }}</span>
          </span>
          <button type="button" class="btn btn-sm btn-primary" (click)="selected.emit(product())">
            {{ isPizza() ? 'Build it' : 'Add' }}
          </button>
        </div>
      </div>
    </div>
  `,
})
export class ProductCard {
  /** `input.required` makes a missing binding a COMPILE error, not an undefined at runtime. */
  readonly product = input.required<Product>();
  readonly selected = output<Product>();

  readonly isPizza = computed(() => this.product().type === 'PIZZA');
  readonly cheapest = computed(() => Math.min(...this.product().sizes.map((s) => s.price)));
}
