// pizza/pizza-react-frontend/src/components/PizzaBuilderModal.tsx
import { useEffect, useId, useMemo, useRef, useState } from 'react';
import { Badge, Button, Col, Form, Modal, Row, ToggleButton, ToggleButtonGroup } from 'react-bootstrap';
import type { Crust, Product, SizeName, Topping } from '../types';
import { formatMoney, round2 } from '../lib/money';
import { useMenu } from '../context/MenuContext';
import { useCart } from '../context/CartContext';
import { useToast } from '../context/ToastContext';

interface Props {
  product: Product | null;
  onHide: () => void;
}

const TOPPING_GROUPS: Array<{ label: string; category: Topping['category'] }> = [
  { label: 'Meats', category: 'MEAT' },
  { label: 'Veggies', category: 'VEGGIE' },
  { label: 'Cheeses', category: 'CHEESE' },
];

/**
 * The pizza builder: pick a size, a crust and toppings, and watch the price update live.
 *
 * Drinks reuse this same modal but only get the size step — one component rather than two
 * near-identical ones.
 */
export function PizzaBuilderModal({ product, onHide }: Props) {
  // Crusts and toppings come from the API via context, not from a hard-coded list.
  const { crusts, toppings } = useMenu();
  const { addItem } = useCart();
  const { showToast } = useToast();

  const [size, setSize] = useState<SizeName>('MEDIUM');
  const [crustId, setCrustId] = useState<string | null>(null);
  const [selectedToppingIds, setSelectedToppingIds] = useState<string[]>([]);
  const [quantity, setQuantity] = useState(1);

  const isPizza = product?.type === 'PIZZA';

  /*
   * REACT CONCEPT: useId
   *
   * Generates a stable, unique, SSR-safe id. Needed to tie <Form.Label htmlFor> to its input:
   * hardcoding id="quantity" would break the moment two of these render on one page, and
   * Math.random() would produce a different id on server and client.
   */
  const quantityId = useId();

  /*
   * REACT CONCEPT: useRef for DOM access
   *
   * A ref holds a mutable value that survives re-renders WITHOUT causing one when it changes.
   * Here it points at the confirm button so focus can be moved there when the modal opens —
   * important for keyboard and screen-reader users, who would otherwise be left at the top of
   * the document with no idea a dialog appeared.
   *
   * In React 19 a ref can be passed straight to a component as a normal prop; the forwardRef
   * wrapper that older tutorials use is no longer required.
   */
  const confirmButtonRef = useRef<HTMLButtonElement>(null);

  // Reset the form whenever a different product is opened, otherwise the previous pizza's
  // toppings would carry over to the next one.
  useEffect(() => {
    if (product) {
      setSize('MEDIUM');
      // Default to the first crust once the catalogue has loaded.
      setCrustId(crusts[0]?.id ?? null);
      setSelectedToppingIds([]);
      setQuantity(1);
    }
  }, [product, crusts]);

  const crust: Crust | null = useMemo(
    () => (isPizza ? (crusts.find((c) => c.id === crustId) ?? null) : null),
    [isPizza, crustId, crusts],
  );

  const selectedToppings = useMemo(
    () => (isPizza ? toppings.filter((t) => selectedToppingIds.includes(t.id)) : []),
    [isPizza, selectedToppingIds, toppings],
  );

  /*
   * REACT CONCEPT: useMemo for derived values
   *
   * The live price is recomputed only when something it depends on actually changes, rather than
   * on every keystroke elsewhere in the modal. This particular sum is cheap; the pattern matters
   * once the calculation is not.
   */
  const pricing = useMemo(() => {
    if (!product) return { unit: 0, total: 0 };

    const base = product.sizes.find((s) => s.size === size)?.price ?? 0;
    const toppingsTotal = selectedToppings.reduce((sum, t) => sum + t.price, 0);
    const unit = round2(base + (crust?.priceDelta ?? 0) + toppingsTotal);

    return { unit, total: round2(unit * quantity) };
  }, [product, size, crust, selectedToppings, quantity]);

  function toggleTopping(id: string) {
    setSelectedToppingIds((current) =>
      current.includes(id) ? current.filter((t) => t !== id) : [...current, id],
    );
  }

  function handleAdd() {
    if (!product) return;

    addItem({ product, size, crust, toppings: selectedToppings, quantity });
    showToast(`${quantity} × ${product.name} added to your cart`);
    onHide();
  }

  return (
    <Modal
      show={product !== null}
      onHide={onHide}
      size="lg"
      centered
      scrollable
      // Bootstrap's Modal already traps focus and restores it on close; this just picks the
      // element that should receive focus first.
      onEntered={() => confirmButtonRef.current?.focus()}
      aria-labelledby="builder-title"
    >
      <Modal.Header closeButton>
        <Modal.Title id="builder-title" className="h5">
          {product?.name}
        </Modal.Title>
      </Modal.Header>

      <Modal.Body>
        <p className="text-muted">{product?.description}</p>

        <section className="mb-4">
          <h4 className="h6 fw-bold text-uppercase text-muted">Size</h4>
          <ToggleButtonGroup
            type="radio"
            name="size"
            value={size}
            onChange={(value: SizeName) => setSize(value)}
            className="w-100"
          >
            {product?.sizes.map((option) => (
              <ToggleButton
                key={option.size}
                id={`size-${option.size}`}
                value={option.size}
                variant="outline-primary"
                className="size-option"
              >
                {option.size.charAt(0) + option.size.slice(1).toLowerCase()}
                <div className="small">{formatMoney(option.price)}</div>
              </ToggleButton>
            ))}
          </ToggleButtonGroup>
        </section>

        {/* Crust and toppings only make sense for a pizza. */}
        {isPizza && (
          <>
            <section className="mb-4">
              <h4 className="h6 fw-bold text-uppercase text-muted">Crust</h4>
              <Row xs={2} md={4} className="g-2">
                {crusts.map((option) => (
                  <Col key={option.id}>
                    <Form.Check
                      type="radio"
                      name="crust"
                      id={`crust-${option.id}`}
                      checked={crustId === option.id}
                      onChange={() => setCrustId(option.id)}
                      label={
                        <span>
                          {option.name}
                          {option.priceDelta > 0 && (
                            <span className="text-muted small d-block">
                              +{formatMoney(option.priceDelta)}
                            </span>
                          )}
                        </span>
                      }
                    />
                  </Col>
                ))}
              </Row>
            </section>

            <section className="mb-4">
              <h4 className="h6 fw-bold text-uppercase text-muted">
                Toppings{' '}
                {selectedToppings.length > 0 && (
                  <Badge bg="primary">{selectedToppings.length} selected</Badge>
                )}
              </h4>
              {TOPPING_GROUPS.map((group) => (
                <div key={group.category} className="mb-3">
                  <div className="small fw-semibold mb-1">{group.label}</div>
                  <div className="d-flex flex-wrap gap-2">
                    {toppings.filter((t) => t.category === group.category).map((topping) => {
                      const selected = selectedToppingIds.includes(topping.id);
                      return (
                        <Button
                          key={topping.id}
                          type="button"
                          size="sm"
                          variant={selected ? 'primary' : 'outline-secondary'}
                          className="topping-chip"
                          aria-pressed={selected}
                          onClick={() => toggleTopping(topping.id)}
                        >
                          {topping.name}
                          <span className="ms-1 small opacity-75">
                            +{formatMoney(topping.price)}
                          </span>
                        </Button>
                      );
                    })}
                  </div>
                </div>
              ))}
            </section>
          </>
        )}

        <section>
          <Form.Label htmlFor={quantityId} className="h6 fw-bold text-uppercase text-muted">
            Quantity
          </Form.Label>
          <Form.Select
            id={quantityId}
            value={quantity}
            onChange={(e) => setQuantity(Number(e.target.value))}
            style={{ maxWidth: '8rem' }}
          >
            {[1, 2, 3, 4, 5].map((n) => (
              <option key={n} value={n}>
                {n}
              </option>
            ))}
          </Form.Select>
        </section>
      </Modal.Body>

      <Modal.Footer className="justify-content-between">
        <div>
          <div className="text-muted small">
            {formatMoney(pricing.unit)} each
          </div>
          <div className="fs-5 fw-bold">{formatMoney(pricing.total)}</div>
        </div>
        <div className="d-flex gap-2">
          <Button variant="outline-secondary" onClick={onHide}>
            Cancel
          </Button>
          <Button ref={confirmButtonRef} variant="primary" onClick={handleAdd}>
            Add to cart
          </Button>
        </div>
      </Modal.Footer>
    </Modal>
  );
}

// pizza/pizza-angular-frontend/src/app/shared/pizza-builder-modal/pizza-builder-modal.ts
import { ChangeDetectionStrategy, Component, computed, effect, inject, input, output, signal } from '@angular/core';
import { Modal } from '../modal/modal';
import { MoneyPipe, humanise } from '../../core/money.pipe';
import { round2 } from '../../core/money';
import { CartService } from '../../core/cart.service';
import { MenuService } from '../../core/menu.service';
import { ToastService } from '../../core/toast.service';
import type { Product, SizeName, Topping, ToppingCategory } from '../../core/models';

const TOPPING_GROUPS: Array<{ label: string; category: ToppingCategory }> = [
  { label: 'Meats', category: 'MEAT' },
  { label: 'Veggies', category: 'VEGGIE' },
  { label: 'Cheeses', category: 'CHEESE' },
];

/**
 * The pizza builder: pick a size, a crust and toppings, and watch the price update live.
 *
 * <p>Drinks reuse this same modal but only get the size step — one component rather than two
 * near-identical ones.
 */
@Component({
  selector: 'app-pizza-builder-modal',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [Modal, MoneyPipe],
  templateUrl: './pizza-builder-modal.html',
})
export class PizzaBuilderModal {
  private readonly menu = inject(MenuService);
  private readonly cart = inject(CartService);
  private readonly toast = inject(ToastService);

  /** `null` means the modal is closed. One piece of state, not two. */
  readonly product = input<Product | null>(null);
  readonly closed = output<void>();

  readonly crusts = this.menu.crusts;
  readonly toppings = this.menu.toppings;
  readonly groups = TOPPING_GROUPS;

  readonly size = signal<SizeName>('MEDIUM');
  readonly crustId = signal<string | null>(null);
  readonly selectedToppingIds = signal<string[]>([]);
  readonly quantity = signal(1);

  readonly isPizza = computed(() => this.product()?.type === 'PIZZA');

  readonly crust = computed(() =>
    this.isPizza() ? (this.crusts().find((c) => c.id === this.crustId()) ?? null) : null,
  );

  readonly selectedToppings = computed<Topping[]>(() =>
    this.isPizza()
      ? this.toppings().filter((t) => this.selectedToppingIds().includes(t.id))
      : [],
  );

  /*
   * The live price, derived rather than stored.
   *
   * The React version wraps this in `useMemo` with a five-entry dependency array. A `computed`
   * needs no array at all — it re-runs when one of the signals it read has changed, and Angular
   * works out which those are by watching the reads. A dependency array that drifts out of step
   * with the body is a whole category of React bug that simply does not exist here.
   */
  readonly unitPrice = computed(() => {
    const product = this.product();
    if (!product) return 0;

    const base = product.sizes.find((s) => s.size === this.size())?.price ?? 0;
    const toppingsTotal = this.selectedToppings().reduce((sum, t) => sum + t.price, 0);
    return round2(base + (this.crust()?.priceDelta ?? 0) + toppingsTotal);
  });

  readonly totalPrice = computed(() => round2(this.unitPrice() * this.quantity()));

  constructor() {
    /*
     * Reset the form whenever a different product is opened, otherwise the previous pizza's
     * toppings would carry over to the next one. Reading `product()` and `crusts()` is what makes
     * this effect re-run when either changes — the equivalent of React's `[product, crusts]`.
     */
    effect(() => {
      const product = this.product();
      const crusts = this.crusts();
      if (!product) return;

      this.size.set('MEDIUM');
      // Default to the first crust once the catalogue has loaded.
      this.crustId.set(crusts[0]?.id ?? null);
      this.selectedToppingIds.set([]);
      this.quantity.set(1);
    });
  }

  toppingsIn(category: ToppingCategory): Topping[] {
    return this.toppings().filter((t) => t.category === category);
  }

  isSelected(id: string): boolean {
    return this.selectedToppingIds().includes(id);
  }

  toggleTopping(id: string): void {
    this.selectedToppingIds.update((current) =>
      current.includes(id) ? current.filter((t) => t !== id) : [...current, id],
    );
  }

  label(value: string): string {
    return humanise(value);
  }

  add(): void {
    const product = this.product();
    if (!product) return;

    this.cart.addItem({
      product,
      size: this.size(),
      crust: this.crust(),
      toppings: this.selectedToppings(),
      quantity: this.quantity(),
    });

    this.toast.show(`${this.quantity()} × ${product.name} added to your cart`);
    this.closed.emit();
  }
}
