// pizza/pizza-react-frontend/src/pages/MenuPage.tsx
import { useCallback, useMemo, useState } from 'react';
import { Col, Container, Nav, Row } from 'react-bootstrap';
import { useSearchParams } from 'react-router-dom';
import { ProductCard } from '../components/ProductCard';
import { PizzaBuilderModal } from '../components/PizzaBuilderModal';
import { MOCK_MENU } from '../mocks/menu';
import type { Product, ProductType } from '../types';

type Filter = 'ALL' | ProductType;

const FILTERS: Array<{ key: Filter; label: string }> = [
  { key: 'ALL', label: 'Everything' },
  { key: 'PIZZA', label: 'Pizzas' },
  { key: 'DRINK', label: 'Drinks' },
];

export function MenuPage() {
  /*
   * REACT ROUTER CONCEPT: useSearchParams
   *
   * The active filter lives in the URL rather than in component state, so /menu?type=PIZZA is
   * shareable, bookmarkable, and survives a refresh. Treating the URL as state is usually the
   * right call for anything a user might want to link to.
   */
  const [searchParams, setSearchParams] = useSearchParams();
  const activeFilter = (searchParams.get('type') as Filter) ?? 'ALL';

  // `null` means the modal is closed. One piece of state, not two.
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);

  /*
   * REACT CONCEPT: useMemo
   * Recompute the filtered list only when the filter changes — not on every re-render caused by
   * opening the modal or the cart drawer.
   */
  const visibleProducts = useMemo(() => {
    if (activeFilter === 'ALL') return MOCK_MENU;
    return MOCK_MENU.filter((product) => product.type === activeFilter);
  }, [activeFilter]);

  /*
   * REACT CONCEPT: useCallback
   * ProductCard is wrapped in React.memo, which compares props by reference. Passing an inline
   * arrow here would create a brand-new function on every render, so every card would see a
   * "changed" prop and re-render — memo would do nothing but waste a comparison.
   */
  const handleSelect = useCallback((product: Product) => {
    setSelectedProduct(product);
  }, []);

  const handleFilter = useCallback(
    (filter: Filter) => {
      if (filter === 'ALL') {
        setSearchParams({});
      } else {
        setSearchParams({ type: filter });
      }
    },
    [setSearchParams],
  );

  return (
    <Container className="py-4">
      <h1 className="h3 fw-bold mb-3">Menu</h1>

      <Nav variant="tabs" activeKey={activeFilter} className="mb-4">
        {FILTERS.map((filter) => (
          <Nav.Item key={filter.key}>
            <Nav.Link eventKey={filter.key} onClick={() => handleFilter(filter.key)}>
              {filter.label}
            </Nav.Link>
          </Nav.Item>
        ))}
      </Nav>

      <Row xs={1} sm={2} lg={4} className="g-4">
        {visibleProducts.map((product) => (
          <Col key={product.id}>
            <ProductCard product={product} onSelect={handleSelect} />
          </Col>
        ))}
      </Row>

      <PizzaBuilderModal product={selectedProduct} onHide={() => setSelectedProduct(null)} />
    </Container>
  );
}

// pizza/pizza-angular-frontend/src/app/pages/menu/menu-page.ts
import { ChangeDetectionStrategy, Component, computed, inject, input, signal } from '@angular/core';
import { Router } from '@angular/router';
import { MenuService } from '../../core/menu.service';
import { ProductCard } from '../../shared/product-card/product-card';
import { PizzaBuilderModal } from '../../shared/pizza-builder-modal/pizza-builder-modal';
import { Spinner } from '../../shared/spinner/spinner';
import type { Product, ProductType } from '../../core/models';

type Filter = 'ALL' | ProductType;

@Component({
  selector: 'app-menu-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ProductCard, PizzaBuilderModal, Spinner],
  templateUrl: './menu-page.html',
})
export class MenuPage {
  private readonly menu = inject(MenuService);
  private readonly router = inject(Router);

  /* ==========================================================================
   * ANGULAR CONCEPT: a query parameter bound straight to an input
   *
   * `withComponentInputBinding()` in app.config.ts makes the router assign matching route params
   * and query params to `input()`s on the routed component. `?type=PIZZA` arrives here as a signal
   * with no `ActivatedRoute` injected and no subscription to clean up — the tidiest form of React
   * Router's `useSearchParams`.
   *
   * The filter lives in the URL rather than in component state on purpose, in both apps:
   * /menu?type=PIZZA is then shareable, bookmarkable, and survives a refresh. Treating the URL as
   * state is usually the right call for anything a user might want to link to.
   * ========================================================================== */
  readonly type = input<Filter | undefined>(undefined);

  readonly filters: Array<{ key: Filter; label: string }> = [
    { key: 'ALL', label: 'Everything' },
    { key: 'PIZZA', label: 'Pizzas' },
    { key: 'DRINK', label: 'Drinks' },
  ];

  readonly activeFilter = computed<Filter>(() => this.type() ?? 'ALL');

  readonly loading = this.menu.loading;
  readonly error = this.menu.error;

  readonly visibleProducts = computed(() => {
    const filter = this.activeFilter();
    const products = this.menu.products();
    return filter === 'ALL' ? products : products.filter((p) => p.type === filter);
  });

  /** `null` means the builder is closed. One piece of state, not two. */
  readonly selectedProduct = signal<Product | null>(null);

  applyFilter(filter: Filter): void {
    void this.router.navigate(['/menu'], {
      queryParams: filter === 'ALL' ? {} : { type: filter },
    });
  }

  reload(): void {
    this.menu.reload();
  }
}
